name: Update README With Quote

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with a new quote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Update README quote
        uses: siddharth2016/quote-readme@main
        with:
          # Your README file
          readme_path: './README.md'
          
          # Your API endpoint
          quote_api_url: "https://tsunquotes.vercel.app/quotes"
          
          # API keys for your specific JSON response
          quote_key: "quote"
          author_key: "author"
          
          # Commit details
          commit_message: "chore(bot): ✨ Update quote of the moment"
          committer_name: "〆༯𝙎คAEED✘🫀"
          committer_email: "tsuncca19@gmail.com"
