name: Update README With Quote

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with a new quote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Is API se quote fetch karega
          feed_list: "https://tsunquotes.vercel.app/quotes"
          
          # Ye tag README mein quote ki jagah batayega
          comment_tag_name: "QUOTE_SECTION"
          
          # Ye template use karke quote ko format karega
          # API se "quote" ab "$title" ban jayega aur "author" ab "$author"
          template: "<i>❝ $title ❞</i><br>— <b>$author</b>"
          
          # Commit ke liye aapke details
          commit_message: "chore(bot): ✨ Update quote of the moment"
          commit_user_name: "〆༯𝙎คAEED✘🫀"
          commit_user_email: "tsuncca19@gmail.com"
