name: Update README Quote 📝

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: Update README with new quote
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        # `checkout` action ko bhi PAT provide kar rahe hain
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Get new quote and update README 🚀
        run: |
          QUOTE_JSON=$(curl -s "https://tsunquotes.vercel.app/quotes")
          QUOTE_TEXT=$(echo $QUOTE_JSON | jq -r .quote)
          QUOTE_AUTHOR=$(echo $QUOTE_JSON | jq -r .author)
          FORMATTED_QUOTE="<i>❝ $QUOTE_TEXT ❞</i><br>— <b>$QUOTE_AUTHOR</b>"
          
          awk -v quote="$FORMATTED_QUOTE" '
            BEGIN {p=1}
            // {print; print quote; p=0}
            // {p=1}
            p {print}
          ' README.md > README.md.tmp && mv README.md.tmp README.md

      - name: Commit and push if changed 💾
        run: |
          # Commit ke liye aapka naam aur email set kar rahe hain
          git config --global user.name "〆༯𝙎คAEED✘🫀"
          git config --global user.email "tsuncca19@gmail.com"
          git add README.md
          
          # Check karein agar koi changes hain
          if git diff --staged --quiet; then
            echo "No changes to commit. Working tree clean. ✅"
          else
            # Changes commit karein
            git commit -m "chore(bot): ✨ Update quote of the moment"
            # Updated push command jo PAT use karega
            git push https://${{ secrets.GH_PAT }}@github.com/SaeedX302/SaeedX302.git HEAD:main
            echo "Changes committed and pushed successfully. 🚀"
          fi
